
// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     browser/android/activity_type_ids.h

package org.chromium.chrome.browser;

public class ActivityTypeIds {
  public static final int NONE = 0;
  public static final int UNKNOWN = 1;
  public static final int MAIN = 2;
  public static final int PREFERENCES = 3;
  public static final int WEBAPPACTIVITY = 4;
  public static final int FULLSCREENACTIVITY = 5;
  public static final int MAX_VALUE = 6;
}
