
// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     ../components/content_settings/core/common/content_settings_types.h

package org.chromium.chrome.browser;

public class ContentSettingsType {
  public static final int CONTENT_SETTINGS_TYPE_DEFAULT = -1;
  public static final int CONTENT_SETTINGS_TYPE_COOKIES = 0;
  public static final int CONTENT_SETTINGS_TYPE_IMAGES = 1;
  public static final int CONTENT_SETTINGS_TYPE_JAVASCRIPT = 2;
  public static final int CONTENT_SETTINGS_TYPE_PLUGINS = 3;
  public static final int CONTENT_SETTINGS_TYPE_POPUPS = 4;
  public static final int CONTENT_SETTINGS_TYPE_GEOLOCATION = 5;
  public static final int CONTENT_SETTINGS_TYPE_NOTIFICATIONS = 6;
  public static final int CONTENT_SETTINGS_TYPE_AUTO_SELECT_CERTIFICATE = 7;
  public static final int CONTENT_SETTINGS_TYPE_FULLSCREEN = 8;
  public static final int CONTENT_SETTINGS_TYPE_MOUSELOCK = 9;
  public static final int CONTENT_SETTINGS_TYPE_MIXEDSCRIPT = 10;
  public static final int CONTENT_SETTINGS_TYPE_MEDIASTREAM = 11;
  public static final int CONTENT_SETTINGS_TYPE_MEDIASTREAM_MIC = 12;
  public static final int CONTENT_SETTINGS_TYPE_MEDIASTREAM_CAMERA = 13;
  public static final int CONTENT_SETTINGS_TYPE_PROTOCOL_HANDLERS = 14;
  public static final int CONTENT_SETTINGS_TYPE_PPAPI_BROKER = 15;
  public static final int CONTENT_SETTINGS_TYPE_AUTOMATIC_DOWNLOADS = 16;
  public static final int CONTENT_SETTINGS_TYPE_MIDI_SYSEX = 17;
  public static final int CONTENT_SETTINGS_TYPE_PUSH_MESSAGING = 18;
  public static final int CONTENT_SETTINGS_TYPE_SSL_CERT_DECISIONS = 19;
  public static final int CONTENT_SETTINGS_TYPE_PROTECTED_MEDIA_IDENTIFIER = 20;
  public static final int CONTENT_SETTINGS_TYPE_APP_BANNER = 21;
  public static final int CONTENT_SETTINGS_TYPE_SITE_ENGAGEMENT = 22;
  public static final int CONTENT_SETTINGS_TYPE_DURABLE_STORAGE = 23;
  public static final int CONTENT_SETTINGS_NUM_TYPES_DO_NOT_USE = 24;
}
