
// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     browser/ui/android/website_settings_popup_android.h

package org.chromium.chrome.browser;

public class PageInfoConnectionType {
  public static final int CONNECTION_UNKNOWN = 0;
  public static final int CONNECTION_ENCRYPTED = 1;
  public static final int CONNECTION_MIXED_CONTENT = 2;
  public static final int CONNECTION_UNENCRYPTED = 3;
  public static final int CONNECTION_ENCRYPTED_ERROR = 4;
  public static final int CONNECTION_INTERNAL_PAGE = 5;
}
