
// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     browser/android/shortcut_info.h

package org.chromium.chrome.browser;

public class ShortcutSource {
  public static final int UNKNOWN = 0;
  public static final int ADD_TO_HOMESCREEN = 1;
  public static final int APP_BANNER = 2;
  public static final int BOOKMARK_NAVIGATOR_WIDGET = 3;
  public static final int BOOKMARK_SHORTCUT_WIDGET = 4;
  public static final int COUNT = 5;
}
