
// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     browser/android/tab_android.h

package org.chromium.chrome.browser;

public class TabLoadStatus {
  public static final int PAGE_LOAD_FAILED = 0;
  public static final int DEFAULT_PAGE_LOAD = 1;
  public static final int PARTIAL_PRERENDERED_PAGE_LOAD = 2;
  public static final int FULL_PRERENDERED_PAGE_LOAD = 3;
}
