
// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     browser/ui/android/infobars/infobar_android.h

package org.chromium.chrome.browser.infobar;

public class ActionType {
  public static final int NONE = 0;
  public static final int OK = 1;
  public static final int CANCEL = 2;
  public static final int TRANSLATE = 3;
  public static final int TRANSLATE_SHOW_ORIGINAL = 4;
  public static final int OVERWRITE = 5;
  public static final int CREATE_NEW_FILE = 6;
}
