
// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     browser/profiles/profile_metrics.h

package org.chromium.chrome.browser.profiles;

public class ProfileAccountManagementMetrics {
  public static final int VIEW = 0;
  public static final int ADD_ACCOUNT = 1;
  public static final int GO_INCOGNITO = 2;
  public static final int CLICK_PRIMARY_ACCOUNT = 3;
  public static final int CLICK_SECONDARY_ACCOUNT = 4;
  public static final int TOGGLE_SIGNOUT = 5;
  public static final int SIGNOUT_SIGNOUT = 6;
  public static final int SIGNOUT_CANCEL = 7;
  public static final int DIRECT_ADD_ACCOUNT = 8;
  public static final int NUM_METRICS = 9;
}
