
// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     offline_pages/offline_page_model.h

package org.chromium.components.offlinepages;

public class DeletePageResult {
  public static final int SUCCESS = 0;
  public static final int CANCELLED = 1;
  public static final int STORE_FAILURE = 2;
  public static final int DEVICE_FAILURE = 3;
  public static final int NOT_FOUND = 4;
  public static final int RESULT_COUNT = 5;
}
