
// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     offline_pages/offline_page_model.h

package org.chromium.components.offlinepages;

public class SavePageResult {
  public static final int SUCCESS = 0;
  public static final int CANCELLED = 1;
  public static final int DEVICE_FULL = 2;
  public static final int CONTENT_UNAVAILABLE = 3;
  public static final int ARCHIVE_CREATION_FAILED = 4;
  public static final int STORE_FAILURE = 5;
  public static final int ALREADY_EXISTS = 6;
  public static final int SKIPPED = 7;
  public static final int RESULT_COUNT = 8;
}
