
// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     enhanced_bookmarks/enhanced_bookmark_utils.h

package org.chromium.chrome.browser.enhancedbookmarks;

public class LaunchLocation {
  public static final int ALL_ITEMS = 0;
  public static final int UNCATEGORIZED = 1;
  public static final int FOLDER = 2;
  public static final int FILTER = 3;
  public static final int SEARCH = 4;
  public static final int BOOKMARK_EDITOR = 5;
  public static final int COUNT = 6;
}
