
// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     browser/android/feedback/connectivity_checker.cc

package org.chromium.chrome.browser.feedback;

public class ConnectivityCheckResult {
  public static final int UNKNOWN = 0;
  public static final int CONNECTED = 1;
  public static final int NOT_CONNECTED = 2;
  public static final int TIMEOUT = 3;
  public static final int ERROR = 4;
  public static final int END = 5;
}
