
// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     browser/android/most_visited_sites.cc

package org.chromium.chrome.browser.ntp;

public class MostVisitedTileType {
  public static final int NONE = 0;
  public static final int ICON_REAL = 1;
  public static final int ICON_COLOR = 2;
  public static final int ICON_DEFAULT = 3;
  public static final int THUMBNAIL_LOCAL = 4;
  public static final int THUMBNAIL_SERVER = 5;
  public static final int THUMBNAIL_DEFAULT = 6;
  public static final int NUM_TILE_TYPES = 7;
}
