
// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     ../components/content_settings/core/common/content_settings.h

package org.chromium.chrome.browser.preferences.website;

public class ContentSettingValues {
  public static final int DEFAULT = 0;
  public static final int ALLOW = 1;
  public static final int BLOCK = 2;
  public static final int ASK = 3;
  public static final int SESSION_ONLY = 4;
  public static final int DETECT_IMPORTANT_CONTENT = 5;
  public static final int NUM_SETTINGS = 6;
}
